CREATE TABLE [dbo].[CARS] (
    [CAR_ID]              INT  IDENTITY (1, 1) NOT NULL,
    [MODEL_ID]            INT  NULL,
    [DATE_MANUFACTURED]   DATE NOT NULL,
    [ACTUAL_FEATURE_ID]   INT  NULL,
    [POSSIBLE_FEATURE_ID] INT  NULL,
    CONSTRAINT [PK_Cars] PRIMARY KEY CLUSTERED ([CAR_ID] ASC),
    CONSTRAINT [FK_CARS_ACTUAL_FEATURES] FOREIGN KEY ([ACTUAL_FEATURE_ID]) REFERENCES [dbo].[ACTUAL_FEATURES] ([ACTUAL_FEATURE_ID]),
    CONSTRAINT [FK_CARS_MODELS] FOREIGN KEY ([MODEL_ID]) REFERENCES [dbo].[MODELS] ([MODEL_ID]),
    CONSTRAINT [FK_CARS_POSSIBLE_FEATURES] FOREIGN KEY ([POSSIBLE_FEATURE_ID]) REFERENCES [dbo].[POSSIBLE_FEATURES] ([POSSIBLE_FEATURE_ID])
);

