CREATE TABLE [dbo].[CUSTOMERS] (
    [CUSTOMER_ID]         INT          IDENTITY (1, 1) NOT NULL,
    [FIRSTNAME]           VARCHAR (50) NULL,
    [LASTNAME]            VARCHAR (50) NULL,
    [CAR_ID]              INT          NOT NULL,
    [DATE_BOUGHT_VEHICLE] DATE         NULL,
    [DATE_VIEWED_CAR]     DATE         NULL,
    [CUSTOMER_TYPES_ID]   INT          NULL,
    CONSTRAINT [PK_Customers] PRIMARY KEY CLUSTERED ([CUSTOMER_ID] ASC),
    CONSTRAINT [FK_CUSTOMERS_CARS] FOREIGN KEY ([CAR_ID]) REFERENCES [dbo].[CARS] ([CAR_ID]),
    CONSTRAINT [FK_CUSTOMERS_CUSTOMER_TYPES] FOREIGN KEY ([CUSTOMER_TYPES_ID]) REFERENCES [dbo].[CUSTOMER_TYPES] ([CUSTOMER_TYPES_ID])
);

