CREATE TABLE [dbo].[CUSTOMER_TYPES] (
    [CUSTOMER_TYPES_ID]   INT          IDENTITY (1, 1) NOT NULL,
    [CUSTOMER_TYPES_NAME] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_PotentialCustomers] PRIMARY KEY CLUSTERED ([CUSTOMER_TYPES_ID] ASC)
);

