CREATE TABLE [dbo].[MODELS] (
    [MODEL_ID]   INT           NOT NULL,
    [BRAND_ID]   INT           NOT NULL,
    [MODEL_NAME] VARCHAR (150) NOT NULL,
    CONSTRAINT [PK_Models] PRIMARY KEY CLUSTERED ([MODEL_ID] ASC),
    CONSTRAINT [FK_Models_Brands] FOREIGN KEY ([BRAND_ID]) REFERENCES [dbo].[BRANDS] ([BRAND_ID])
);

