CREATE TABLE [dbo].[POSSIBLE_FEATURES] (
    [POSSIBLE_FEATURE_ID]    INT NOT NULL,
    [NAVIGATION]             BIT NULL,
    [CAMERA]                 BIT NULL,
    [LEATHER_SEATS]          BIT NULL,
    [POSSIBLE_FEATURE_PRICE] INT NULL,
    CONSTRAINT [PK_PossibleFeatures] PRIMARY KEY CLUSTERED ([POSSIBLE_FEATURE_ID] ASC)
);

